live_config_reload = true

import = [
  # "~/.config/alacritty/rose-pine.toml"
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 11
builtin_box_drawing = true

#normal = { family = "IosevkaTerm", style = "Regular" }
#bold = { family = "IosevkaTerm", style = "Bold" }
#italic = { family = "IosevkaTerm", style = "Italic" }
#bold_italic = { family = "IosevkaTerm", style = "Bold Italic" }

normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

[selection]
save_to_clipboard = false

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9

[window.padding]
x = 15
y = 15
