import = ["/home/yoela/.config/alacritty/fonts.toml"]
live_config_reload = true

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"

[selection]
save_to_clipboard = false

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9

[window.padding]
x = 15
y = 15
