format = """
[╭](bold green)$fill[╮](bold green)\
$line_break\
$os\
$all\
$line_break\
[├](bold green)$fill[╯](bold green)\
$line_break\
[╰─](bold green)\
$character"""

[fill]
symbol = '─'
style = 'bold green'

[directory]
#style = "bold blue"
#truncation_length = 8
truncation_symbol = '…/'

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
".config" = "⚙"
".dotfiles" = "⚙○"
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚"
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[character]
#success_symbol = "[❯](bold green)"
#error_symbol = "[❯](bold red)"

[os]
disabled = false
format = '[ $symbol ]($style)'
