#! /bin/sh

# AUTOSTART

# First, kill if already running
killall -9 bspc sxhkd dunst ksuperkey xfce4-power-manager xsettingsd

pgrep -x sxhkd > /dev/null || sxhkd &

wal -i ~/wallpapers
$HOME/.cache/wal/colors.sh

$HOME/.config/polybar/launch.sh

xfce4-power-manager &

exec mpd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# WORKSPACES
bspc monitor -d I II III IV V VI VII VIII IX X

# WINDOWS
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

export PATH="${PATH}:$HOME/.config/rofi/scripts"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off
