#!/usr/bin/bash

echo "Updating system..."
sleep 3
sudo zypper refresh
sudo zypper dist-upgrade
echo "You should reboot your system after kernel updates."
sleep 3

echo "Installing multimedia codecs..."
sleep 3
sudo zypper addrepo -cfp 90 'https://ftp.gwdg.de/pub/linux/misc/packman/suse/openSUSE_Tumbleweed/' packman
sudo zypper refresh
sudo zypper dist-upgrade --from packman --allow-vendor-change
sudo zypper install --from packman ffmpeg gstreamer-plugins-{good,bad,ugly,libav} libavcodec-full vlc-codecs

echo "Installing VSCode..."
sleep 3
sudo zypper ar https://packages.microsoft.com/yumrepos/vscode vscode
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo zypper refresh
sudo zypper install code

echo "Done."
echo "Enjoy your new system!"