#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# --------------------------------------------------
# AUTOSTART
# --------------------------------------------------

"$HOME"/scripts/pywal.sh
. "$HOME"/.cache/wal/colors.sh

./panel.sh

pidof -q xidlehook || { "$HOME"/scripts/locker.sh & }
pidof -q picom || { picom & }
pidof -q dunst || { dunst & }
pidof -q pipewire || { pipewire & }
pidof -q poweralertd || { poweralertd & }
pidof -q syncthing || { syncthing & }
pidof -q redshift || { redshift & }

xsetroot -solid '$color1'

# activate superkey menu
ksuperkey -e 'Super_L=Alt_L|F2'

# keybindings
. "$HOME"/.config/herbstluftwm/keys

# theme
. "$HOME"/.config/herbstluftwm/theme

# rules
. "$HOME"/.config/herbstluftwm/winRules


# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
