#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

#xsetroot -solid '#5A8E3A'

# --------------------------------------------------
# AUTOSTART
# --------------------------------------------------

"$HOME"/scripts/pywal.sh
. "$HOME"/.cache/wal/colors.sh

# (re)load polybar
if hash polybar >/dev/null 2>&1; then
	pkill polybar
	polybar top -c ~/.config/polybar/hack/config.ini 2>&1 || tee -a /tmp/polybar_hack-top.log & disown
	polybar bottom -c ~/.config/polybar/hack/config.ini 2>&1 || tee -a /tmp/polybar_hack-bottom.log & disown
fi

pidof -q xidlehook || { "$HOME"/scripts/locker.sh & }
pidof -q dunst || { dunst & }
pidof -q pipewire || { pipewire & }
pidof -q syncthing || { syncthing serve & }
pidof -q redshift || { redshift & }

# activate superkey menu
ksuperkey -e 'Super_L=Alt_L|F2'

# keybindings
. "$HOME"/.config/herbstluftwm/keys

# theme
. "$HOME"/.config/herbstluftwm/theme

# rules
. "$HOME"/.config/herbstluftwm/winRules

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
