#    _               _              
#   | |__   __ _ ___| |__  _ __ ___ 
#   | '_ \ / _` / __| '_ \| '__/ __|
#  _| |_) | (_| \__ \ | | | | | (__ 
# (_)_.__/ \__,_|___/_| |_|_|  \___|
# 
# -----------------------------------------------------
# ~/.bashrc
# -----------------------------------------------------

# If not running interactively, don't do anything
[[ $- != *i* ]] && return
PS1='[\u@\h \W]\$ '

if [ -e ~/.nix-profile/etc/profile.d/nix.sh ]; then
	source ~/.nix-profile/etc/profile.d/nix.sh
fi

if [ -f ~/.bash_aliases ]; then
	source ~/.bash_aliases
fi

if [ -f ~/.bash_functions ]; then
	source ~/.bash_functions
fi

# -----------------------------------------------------
# ALIASES
# -----------------------------------------------------

alias c='clear'
alias nf='neofetch'
alias pf='pfetch'
alias ls='exa -al'
alias mutt='neomutt'
alias m='neomutt'
alias shutdown='systemctl poweroff'
alias v='nvim'
alias r='ranger'
alias t='sudo timeshift --list'
alias ts='~/dotfiles/scripts/snapshot.sh'
alias matrix='cmatrix'
alias shot='scrot -d 3 -c -z -u'
alias shotsel='scrot -s'
alias wifi='nmtui'
alias od='~/private/onedrive.sh'
alias rw='~/dotfiles/waybar/reload.sh'
alias winclass="xprop | grep 'CLASS'"

# Window Managers

alias Qtile='startx'
# alias Hyprland="~/dotfiles/hypr/starthypr.sh"

# GIT

alias gs="git status"
alias ga="git add"
alias gc="git commit -m"
alias gp="git push"
alias gpl="git pull"
alias gst="git stash"
alias gsp="git stash; git pull"

# SCRIPTS

alias w='~/dotfiles/scripts/updatewal.sh'
alias gr='python ~/dotfiles/scripts/growthrate.py'
alias ChatGPT='python ~/mychatgpt/mychatgpt.py'
alias chat='python ~/mychatgpt/mychatgpt.py'
alias ascii='~/dotfiles/scripts/figlet.sh'

# VIRTUAL MACHINE

alias vm='~/private/launchvm.sh'
alias lg='~/dotfiles/scripts/looking-glass.sh'
alias vmstart='virsh --connect qemu:///system start win11'
alias vmstop='virsh --connect qemu:///system destroy win11'

# EDIT CONFIG FILES

alias confq='nvim ~/dotfiles/qtile/config.py'
alias confp='nvim ~/dotfiles/picom/picom.conf'
alias confb='nvim ~/dotfiles/.bashrc'

# SYSTEM

alias update-grub='sudo grub-mkconfig -o /boot/grub/grub.cfg'
alias setkb='setxkbmap de;echo "Keyboard set back to de."'

# -----------------------------------------------------
# SCREEN RESOLUTINS
# -----------------------------------------------------
alias res1='xrandr --output DisplayPort-0 --mode 2560x1440 --rate 120'
alias res2='xrandr --output DisplayPort-0 --mode 1920x1080 --rate 120'
alias r1='hyprctl keyword monitor ,preferred,auto,1'
alias r2='hyprctl keyword monitor ,1920x1080,auto,1'


export PATH="/usr/lib/ccache/bin/:$PATH"
export PATH="~/bg2md.rb:$PATH"

# -----------------------------------------------------
# START OH-MY-POSH
# -----------------------------------------------------
THEME=nordtron
eval "$(oh-my-posh init bash --config ~/dotfiles/oh-my-posh/themes/$THEME.omp.json)"

# -----------------------------------------------------
# PYWAL
# -----------------------------------------------------
if [ -f ~/.cache/wal/sequences ]; then
	cat ~/.cache/wal/sequences
fi
# -----------------------------------------------------
# PFETCH
# -----------------------------------------------------
echo ""
pfetch
